# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - develop
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureContainerRegistryName: 'crvemotueus2'
  azureContainerRegistryUrl: '$(azureContainerRegistryName).azurecr.io'
  dockerComposeFile: 'src/docker-compose.yml'
  timestamp: $(Get-Date -Format yyyyMMddTHHmmssfffffffZ)
  vemotuappChartPath: 'src/vemotuapp'
  vemotuappChartFilePath: '$(vemotuappChartPath)/Chart.yaml'
  vemotuTlsSecretName: 'vemotu-com-tls'
  remeterTlsSecretName: 'remeter-org-tls'

steps:
- script: |
    echo "##vso[task.setvariable variable=versionPrefix]$(cat src/version)"
  name: ReadVersionFromFile

- powershell: |
    $date=$(Get-Date -Format yyyyMMddTHHmmssfffffffZ);
    Write-Host "##vso[task.setvariable variable=timestamp]$date"
  name: SetTimestamp

- script: |
    echo "##vso[task.setvariable variable=alphaOrBeta]alpha.$(Build.SourceBranchName)"
    echo "##vso[task.setvariable variable=configurationDecision]Debug"
    echo "##vso[task.setvariable variable=vemotuHostDecision]dev.vemotu.com"
    echo "##vso[task.setvariable variable=remeterHostDecision]dev.remeter.org"
    echo "##vso[task.setvariable variable=deployNamespaceDecision]vemotu-dev"
    echo "##vso[task.setvariable variable=loadBalancerIPDecision]52.167.76.207"
  name: SetVariableDefaults

- script: |
    echo "##vso[task.setvariable variable=alphaOrBeta]beta"
    echo "##vso[task.setvariable variable=configurationDecision]Release"
    echo "##vso[task.setvariable variable=vemotuHostDecision]int.vemotu.com"
    echo "##vso[task.setvariable variable=remeterHostDecision]int.remeter.org"
    echo "##vso[task.setvariable variable=deployNamespaceDecision]vemotu-int"
    echo "##vso[task.setvariable variable=loadBalancerIPDecision]52.177.246.77"
  name: SetVariablesForDevelop
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')

- script: |
    echo "##vso[task.setvariable variable=configuration;isOutput=true]$CONFIGURATIONDECISION"
    echo "##vso[task.setvariable variable=version;isOutput=true]$VERSIONPREFIX-$ALPHAORBETA.$(Build.BuildId)"
    echo "##vso[task.setvariable variable=fullVersion;isOutput=true]$VERSIONPREFIX-$ALPHAORBETA.$(Build.BuildId)+$TIMESTAMP"
    echo "##vso[task.setvariable variable=assemblyVersion;isOutput=true]$VERSIONPREFIX.$(Build.BuildId)"
    echo "##vso[task.setvariable variable=vemotuHost;isOutput=true]$VEMOTUHOSTDECISION"
    echo "##vso[task.setvariable variable=remeterHost;isOutput=true]$REMETERHOSTDECISION"
    echo "##vso[task.setvariable variable=deployNamespace;isOutput=true]$DEPLOYNAMESPACEDECISION"
    echo "##vso[task.setvariable variable=loadBalancerIP]$LOADBALANCERIPDECISION"
  name: SetOutputVariables

- powershell: |
    $content = Get-Content $(vemotuappChartFilePath)
    $versionLine = $content | Select-String -Pattern '^version:' -CaseSensitive | Select-Object -ExpandProperty Line
    $appVersionLine = $content | Select-String -Pattern '^appVersion:' -CaseSensitive | Select-Object -ExpandProperty Line

    $content | ForEach-Object {$_ -replace $versionLine, "version: $(SetOutputVariables.version)"} | ForEach-Object {$_ -replace $appVersionLine, "appVersion: $(SetOutputVariables.fullVersion)"} | Set-Content $(vemotuappChartFilePath)
  name: UpdateChartYamlVersions

- task: DockerCompose@0
  name: DockerComposeBuild
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: '$(azureSubscription)'
    azureContainerRegistry: '{"loginServer":"crvemotueus2.azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureResourceGroup)/providers/Microsoft.ContainerRegistry/registries/crvemotueus2"}'
    dockerComposeFile: 'src/docker-compose.yml'
    action: 'Build services'
    arguments: '--build-arg version=$(SetOutputVariables.fullVersion) --build-arg assembly_version=$(SetOutputVariables.assemblyVersion) --build-arg configuration=$(SetOutputVariables.configuration)'
    dockerComposeFileArgs: |
      DOCKER_IMAGE_VERSION_TAG=$(SetOutputVariables.version)
    includeLatestTag: false

- task: DockerCompose@0
  condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
  name: DockerComposePush
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: '$(azureSubscription)'
    azureContainerRegistry: '{"loginServer":"crvemotueus2.azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureResourceGroup)/providers/Microsoft.ContainerRegistry/registries/crvemotueus2"}'
    dockerComposeFile: 'src/docker-compose.yml'
    action: 'Push services'
    dockerComposeFileArgs: |
      DOCKER_IMAGE_VERSION_TAG=$(SetOutputVariables.version)
    includeLatestTag: false

- task: HelmInstaller@0
  name: HelmInstall
  condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
  inputs:
    helmVersion: '3.4.1'
    installKubectl: true
    kubectlVersion: '1.19.4'

- task: HelmDeploy@0
  condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
  name: HelmPushToCR
  inputs:
    azureSubscriptionForACR: '$(azureSubscription)'
    azureResourceGroupForACR: 'rg-vemotu-eus2-001'
    azureContainerRegistry: 'crvemotueus2.azurecr.io'
    command: 'save'
    chartNameForACR: 'vemotuapp:$(SetOutputVariables.version)'
    chartPathForACR: '$(vemotuappChartPath)'

- script: 'helm dependency update src/vemotuapp'
  condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
  name: HelmDependencyUpdate

- task: HelmDeploy@0
  condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
  name: HelmUpgrade
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '$(azureSubscription)'
    azureResourceGroup: '$(azureResourceGroup)'
    kubernetesCluster: '$(nonProdKubernetesCluster)'
    namespace: '$(SetOutputVariables.deployNamespace)'
    command: 'upgrade'
    chartType: 'Name'
    chartName: 'vemotuapp'
    chartVersion: '$(SetOutputVariables.version)'
    updateDependency: true
    overrideValues: |
        ingress.hosts[0].host=$(SetOutputVariables.vemotuHost)
        ingress.hosts[0].paths[0]=/
        ingress.hosts[1].host=$(SetOutputVariables.remeterHost)
        ingress.hosts[1].paths[0]=/
        ingress.tls[0].hosts[0]=$(SetOutputVariables.vemotuHost)
        ingress.tls[0].secretName=$(vemotuTlsSecretName)
        ingress.tls[1].hosts[0]=$(SetOutputVariables.remeterHost)
        ingress.tls[1].secretName=$(remeterTlsSecretName)
        ingress-nginx.controller.service.loadBalancerIP=$(SetOutputVariables.loadBalancerIP)
