# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - develop
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureContainerRegistryName: 'crvemotueus2'
  azureContainerRegistryUrl: '$(azureContainerRegistryName).azurecr.io'
  dockerComposeFile: 'src/docker-compose.yml'
  timestamp: $(Get-Date -Format yyyyMMddTHHmmssfffffffZ)
  

steps:
- script: |
    echo "##vso[task.setvariable variable=versionPrefix]$(cat src/version)"
  name: ReadVersionFromFile

- script: |
    echo "##vso[task.setvariable variable=alphaOrBeta]alpha"
  name: DefaultToAlpha

- script: |
    echo "##vso[task.setvariable variable=alphaOrBeta]beta"
  name: UseBetaForDevelop
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')

- script: |
    echo "##vso[task.setvariable variable=configurationDecision]Debug"
  name: DefaultToDebug

- script: |
    echo "##vso[task.setvariable variable=configurationDecision]Release"
  name: UseReleaseForDevelop
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')

- script: |
    echo "##vso[task.setvariable variable=configuration;isOutput=true]$CONFIGURATIONDECISION"
  name: SetConfiguration

- script: |
    $date=$(Get-Date -Format yyyyMMddTHHmmssfffffffZ);
    Write-Host "##vso[task.setvariable variable=timestamp]$date"
  name: SetTimestamp

- script: |
    echo "##vso[task.setvariable variable=version;isOutput=true]$VERSIONPREFIX-$ALPHAORBETA+build.$(Build.BuildId)-$TIMESTAMP"
  name: SetVersion

- script: |
    echo "##vso[task.setvariable variable=assemblyVersion;isOutput=true]$VERSIONPREFIX.$(Build.BuildId)"
  name: SetAssemblyVersion

- task: DockerCompose@0
  name: DockerComposeBuild
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: '$(azureSubscription)'
    azureContainerRegistry: '{"loginServer":"crvemotueus2.azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureCRResourceGroup)/providers/Microsoft.ContainerRegistry/registries/crvemotueus2"}'
    dockerComposeFile: 'src/docker-compose.yml'
    action: 'Build services'
    arguments: '--build-arg version=$(SetVersion.version) --build-arg assembly_version=$(SetAssemblyVersion.assemblyVersion) --build-arg configuration=$(SetConfiguration.configuration)'

- task: DockerCompose@0
  condition: in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule')
  name: DockerComposePush
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: '$(azureSubscription)'
    azureContainerRegistry: '{"loginServer":"crvemotueus2.azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureCRResourceGroup)/providers/Microsoft.ContainerRegistry/registries/crvemotueus2"}'
    dockerComposeFile: 'src/docker-compose.yml'
    action: 'Push services'
