resources:
  repositories:
  - repository: DevelopBranch
    type: github
    endpoint: rileywhite oauth connection
    name: rileywhite/remeter-portal
    ref: develop


trigger:
  batch: true
  branches:
    include:
      - main
    exclude:
      - 'refs/pull/*'


variables:
  azureContainerRegistryName: 'crvemotueus2'
  azureContainerRegistryUrl: '$(azureContainerRegistryName).azurecr.io'

  helmVersion: '3.4.1'
  kubectlVersion: '1.19.4'

  buildConfiguration: Release
  timestamp: $(Get-Date -Format yyyyMMddTHHmmssfffffffZ)

  mainBranchPath: 'remeter-portal'
  developBranchPath: 'develop'
  srcPath: '$(mainBranchPath)/src'
  versionFilePath: '$(srcPath)/version'
  dockerComposeFilePath: '$(srcPath)/docker-compose.yml'
  vemotuappChartPath: '$(srcPath)/vemotuapp'
  vemotuappChartFilePath: '$(vemotuappChartPath)/Chart.yaml'
  vemotuappValuesFilePath: '$(vemotuappChartPath)/values.yaml'
  developSrcPath: '$(developBranchPath)/src'
  developVersionFilePath: '$(developSrcPath)/version'

  vemotuTlsSecretName: 'vemotu-com-tls'
  remeterTlsSecretName: 'remeter-org-tls'

  stagingDeployNamespace: vemotu-staging
  stagingReleaseName: vemotuapp-staging
  stagingVemotuHost: staging.vemotu.com
  stagingRemeterHost: staging.remeter.org
  stagingLoadBalancerIP: 52.138.105.11

  prodDeployNamespace: vemotu-prod
  prodReleaseName: vemotuapp-prod
  prodVemotuHost: prod.vemotu.com
  prodRemeterHost: prod.remeter.org
  prodLoadBalancerIP: 52.184.202.52


jobs:
- job: DeployToStaging
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    name: CheckoutMainBranchAndPersistCredentials

  - script: |
      echo "##vso[task.setvariable variable=versionPrefix]$(cat $(versionFilePath))"
    name: ReadVersionFromFile

  - powershell: |
      $date=$(Get-Date -Format yyyyMMddTHHmmssfffffffZ);
      Write-Host "##vso[task.setvariable variable=timestamp]$date"
    name: SetTimestamp

  - script: |
      echo "##vso[task.setvariable variable=version;isOutput=true]$VERSIONPREFIX"
      echo "##vso[task.setvariable variable=fullVersion;isOutput=true]$VERSIONPREFIX+build.$(Build.BuildId)-timestamp.$TIMESTAMP"
      echo "##vso[task.setvariable variable=assemblyVersion;isOutput=true]$VERSIONPREFIX.$(Build.BuildId)"
      echo "##vso[task.setvariable variable=loadBalancerIP;isOutput=true]$(stagingLoadBalancerIP)"
    name: SetOutputVariables

  - powershell: |
      $content = Get-Content $(vemotuappChartFilePath)
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could write read $(vemotuappChartFilePath)'
          Get-Location | Write-Error
          Exit 1
      }

      $versionLine = $content | Select-String -Pattern '^version:' -CaseSensitive | Select-Object -ExpandProperty Line
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could not read version line matching expected pattern \'^version:\''
          Get-Location | Write-Error
          Exit 1
      }

      $appVersionLine = $content | Select-String -Pattern '^appVersion:' -CaseSensitive | Select-Object -ExpandProperty Line
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could not read appVersion line matching expected pattern \'^appVersion:\''
          Get-Location | Write-Error
          Exit 1
      }

      $content | ForEach-Object {$_ -replace $versionLine, "version: $(SetOutputVariables.version)"} | ForEach-Object {$_ -replace $appVersionLine, "appVersion: $(SetOutputVariables.version)"} | Set-Content $(vemotuappChartFilePath)
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could not set updated content in $(vemotuappChartFilePath)'
          Get-Location | Write-Error
          Exit 1
      }

      $content = Get-Content $(vemotuappValuesFilePath)
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could not read $(vemotuappValuesFilePath)'
          Get-Location | Write-Error
          Exit 1
      }

      $imageTagLine = $content | Select-String -Pattern '^  tag:' -CaseSensitive | Select-Object -ExpandProperty Line
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could not read tag line matching expected pattern \'^  tag::\''
          Get-Location | Write-Error
          Exit 1
      }

      $content | ForEach-Object {$_ -replace $imageTagLine, "  tag: $(SetOutputVariables.version)"} | Set-Content $(vemotuappValuesFilePath)
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could not set updated content in $(vemotuappValuesFilePath)'
          Get-Location | Write-Error
          Exit 1
      }

    name: UpdateChartYamlFiles

  - task: DockerCompose@0
    name: DockerComposeBuild
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: '$(azureSubscription)'
      azureContainerRegistry: '{"loginServer":"$(azureContainerRegistryName).azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureResourceGroup)/providers/Microsoft.ContainerRegistry/registries/$(azureContainerRegistryName)"}'
      dockerComposeFilePath: '$(dockerComposeFilePath)'
      action: 'Build services'
      arguments: '--build-arg version=$(SetOutputVariables.fullVersion) --build-arg assembly_version=$(SetOutputVariables.assemblyVersion) --build-arg configuration=$(buildConfiguration)'
      dockerComposeFileArgs: |
        DOCKER_IMAGE_VERSION_TAG=$(SetOutputVariables.version)
      includeLatestTag: true

  - script: |
      cd $(srcPath)
      git tag v$(SetOutputVariables.version)
      git push origin v$(SetOutputVariables.version)
      cd $(Agent.BuildDirectory)
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: GitTagVersionOnMainBranch
    workingDirectory: $(Build.SourcesDirectory)

  - task: GitHubRelease@1
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: CreateDraftRelease
    inputs:
      gitHubConnection: '$(gitHubServiceConnection)'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'v$(SetOutputVariables.version)'
      isDraft: true
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'

  - script: |
      echo "##vso[task.setvariable variable=success;isOutput=true]true"
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: SetDraftReleaseCreated
    workingDirectory: $(Build.SourcesDirectory)

  - checkout: DevelopBranch
    name: CheckoutDevelopBranchAndPersistCredentials
    persistCredentials: true
    path: '$(developBranchPath)'

  - powershell: |
      $content =  Get-Content $(developVersionFilePath);
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could not read version file $(developVersionFilePath)'
          Get-Location | Write-Error
          Exit 1
      }

      $valid = $content -match '([0-9]+\.[0-9]+\.)([0-9]+)'
      if (-Not $valid)
      {
          Write-Error 'Invalid version. Expected Major.Minor.Patch'
          Get-Location | Write-Error
          Exit 1
      }

      $newVersion = $Matches[1] + ([convert]::ToInt64($Matches[2], 10) + 1)
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could generate new patch version'
          Get-Location | Write-Error
          Exit 1
      }

      Set-Content $(developVersionFilePath) $newVersion
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could write new patch version to version file'
          Get-Location | Write-Error
          Exit 1
      }

      cd $(developBranchPath)
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could not cd to $(developBranchPath)'
          Get-Location | Write-Error
          Exit 1
      }

      git commit -m "Set new patch version $newVersion"
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could not commit version patch bump'
          Get-Location | Write-Error
          Exit 1
      }

      git push
      if ($LASTEXITCODE -ne 0)
      {
          Write-Error 'Could not push version patch bump commit'
          Get-Location | Write-Error
          Exit 1
      }

      cd $(Agent.BuildDirectory)
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: GitIncrementPatchVersionOnDevelopBranch
    workingDirectory: $(Build.SourcesDirectory)

  - task: DockerCompose@0
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: DockerComposePush
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: '$(azureSubscription)'
      azureContainerRegistry: '{"loginServer":"$(azureContainerRegistryName).azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureResourceGroup)/providers/Microsoft.ContainerRegistry/registries/$(azureContainerRegistryName)"}'
      dockerComposeFilePath: '$(dockerComposeFilePath)'
      action: 'Push services'
      dockerComposeFileArgs: |
        DOCKER_IMAGE_VERSION_TAG=$(SetOutputVariables.version)
      includeLatestTag: true

  - task: HelmInstaller@0
    name: HelmInstall
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    inputs:
      helmVersion: '$(helmVersion)'
      installKubectl: true
      kubectlVersion: '$(kubectlVersion)'

  - task: HelmDeploy@0
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: HelmPushToCR
    inputs:
      azureSubscriptionForACR: '$(azureSubscription)'
      azureResourceGroupForACR: '$(azureResourceGroup)'
      azureContainerRegistry: '$(azureContainerRegistryName).azurecr.io'
      command: 'save'
      chartNameForACR: 'vemotuapp:$(SetOutputVariables.version)'
      chartPathForACR: '$(vemotuappChartPath)'

  - script: 'helm dependency update $(vemotuappChartPath)'
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: HelmDependencyUpdate

  - task: HelmDeploy@0
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: HelmUpgrade
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscription: '$(azureSubscription)'
      azureResourceGroup: '$(azureResourceGroup)'
      kubernetesCluster: '$(nonProdKubernetesCluster)'
      namespace: '$(stagingDeployNamespace)'
      command: 'upgrade'
      releaseName: '$(stagingReleaseName)'
      chartType: 'FilePath'
      chartPath: '$(vemotuappChartPath)'
      chartVersion: '$(SetOutputVariables.version)'
      updateDependency: true
      overrideValues: |
          ingress.hosts[0].host=$(stagingVemotuHost)
          ingress.hosts[0].paths[0]=/
          ingress.hosts[1].host=$(stagingRemeterHost)
          ingress.hosts[1].paths[0]=/
          ingress.tls[0].hosts[0]=$(stagingVemotuHost)
          ingress.tls[0].secretName=$(vemotuTlsSecretName)
          ingress.tls[1].hosts[0]=$(stagingRemeterHost)
          ingress.tls[1].secretName=$(remeterTlsSecretName)
          ingress-nginx.controller.service.loadBalancerIP="$(stagingLoadBalancerIP)"


- job: GetApproval
  dependsOn: DeployToStaging
  continueOnError: true
  pool: server
  steps:
  - task: ManualValidation@0
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: ApproveForRelease
    inputs:
      notifyUsers: 'rileywhite@gmail.com'
      instructions: 'Approve?'


- job: DeployToProd
  dependsOn:
    - DeployToStaging
    - GetApproval
  condition: eq(dependencies.GetApproval.result, 'Succeeded')
  continueOnError: true
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: HelmDeploy@0
    name: HelmUpgrade
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscription: '$(azureSubscription)'
      azureResourceGroup: '$(azureResourceGroup)'
      kubernetesCluster: '$(prodKubernetesCluster)'
      namespace: '$(prodDeployNamespace)'
      command: 'upgrade'
      releaseName: '$(prodReleaseName)'
      chartType: 'FilePath'
      chartPath: '$(vemotuappChartPath)'
      chartVersion: '$(SetOutputVariables.version)'
      updateDependency: true
      overrideValues: |
          ingress.hosts[0].host=$(prodVemotuHost)
          ingress.hosts[0].paths[0]=/
          ingress.hosts[1].host=$(prodRemeterHost)
          ingress.hosts[1].paths[0]=/
          ingress.tls[0].hosts[0]=$(prodVemotuHost)
          ingress.tls[0].secretName=$(vemotuTlsSecretName)
          ingress.tls[1].hosts[0]=$(prodRemeterHost)
          ingress.tls[1].secretName=$(remeterTlsSecretName)
          ingress-nginx.controller.service.loadBalancerIP="$(prodLoadBalancerIP)"


- job: RemoveDraftRelease
  dependsOn:
    - GetApproval
    - DeployToProd
  condition: |
    and
    (
      eq(dependencies.GetApproval.result, 'Failed'),
      in(dependencies.DeployToProd.result, 'Skipped', 'Failed')
    )
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: GitHubRelease@1
    name: DeleteFailedDraftRelease
    inputs:
      gitHubConnection: '$(gitHubServiceConnection)'
      repositoryName: '$(Build.Repository.Name)'
      action: 'delete'
      tag: 'v$(SetOutputVariables.version)'


- job: UpdateToNonDraftRelease
  dependsOn:
    - GetApproval
    - DeployToProd
  condition: |
    and
    (
      eq(dependencies.GetApproval.result, 'Succeeded'),
      in(dependencies.DeployToProd.result, 'Succeeded')
    )
  steps:
  - task: GitHubRelease@1
    name: UpdateToNonDraftRelease
    inputs:
      gitHubConnection: '$(gitHubServiceConnection)'
      repositoryName: '$(Build.Repository.Name)'
      action: 'edit'
      target: '$(Build.SourceVersion)'
      tag: 'v$(SetOutputVariables.version)'
      assetUploadMode: 'replace'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
