trigger:
  batch: true
  branches:
    include:
      - main
    exclude:
      - 'refs/pull/*'


variables:
  azureContainerRegistryName: 'crvemotueus2'
  azureContainerRegistryUrl: '$(azureContainerRegistryName).azurecr.io'

  helmVersion: '3.4.1'
  kubectlVersion: '1.19.4'

  buildConfiguration: Release
  timestamp: $(Get-Date -Format yyyyMMddTHHmmssfffffffZ)

  checkoutPath: '.'
  srcPath: '$(checkoutPath)/src'
  versionFilePath: '$(srcPath)/version'
  dockerComposeFilePath: '$(srcPath)/docker-compose.yml'
  footingappChartPath: '$(srcPath)/footingapp'
  footingappChartFilePath: '$(footingappChartPath)/Chart.yaml'
  footingappValuesFilePath: '$(footingappChartPath)/values.yaml'

  footingTlsSecretName: 'footing-app-tls'
  footingWwwTlsSecretName: 'www-footing-app-tls'

  stagingDeployNamespace: footing-staging
  stagingReleaseName: footingapp-staging
  stagingFootingHost: staging.footing.app
  stagingLoadBalancerIP: 52.138.105.11

  prodDeployNamespace: footing-prod
  prodReleaseName: footingapp-prod
  prodFootingHost: footing.app
  prodWwwFootingHost: www.footing.app
  prodLoadBalancerIP: 52.184.202.52

jobs:
- job: BuildAndPushToContainerRegistry
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    name: CheckoutMainBranchAndPersistCredentials
    persistCredentials: true

  - script: |
      echo "##vso[task.setvariable variable=versionPrefix]$(cat $(versionFilePath))"
    name: ReadVersionFromFile

  - powershell: |
      $date=$(Get-Date -Format yyyyMMddTHHmmssfffffffZ);
      Write-Host "##vso[task.setvariable variable=timestamp]$date"
    name: SetTimestamp

  - script: |
      echo "##vso[task.setvariable variable=version;isOutput=true]$VERSIONPREFIX"
      echo "##vso[task.setvariable variable=fullVersion;isOutput=true]$VERSIONPREFIX+build.$(Build.BuildId)-timestamp.$TIMESTAMP"
      echo "##vso[task.setvariable variable=assemblyVersion;isOutput=true]$VERSIONPREFIX.$(Build.BuildId)"
    name: SetOutputVariables

  - script: |
      cd $(srcPath)
      git tag v$(SetOutputVariables.version)
      git push origin v$(SetOutputVariables.version)
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: GitTagVersion

  - powershell: |
      try
      {
          Set-PSDebug -Trace 2
          $content = Get-Content $(footingappChartFilePath)
          $versionLine = $content | Select-String -Pattern '^version:' -CaseSensitive | Select-Object -ExpandProperty Line
          $appVersionLine = $content | Select-String -Pattern '^appVersion:' -CaseSensitive | Select-Object -ExpandProperty Line
          $content | ForEach-Object {$_ -replace $versionLine, "version: $(SetOutputVariables.version)"} | ForEach-Object {$_ -replace $appVersionLine, "appVersion: $(SetOutputVariables.version)"} | Set-Content $(footingappChartFilePath)
          $content = Get-Content $(footingappValuesFilePath)
          $imageTagLine = $content | Select-String -Pattern '^  tag:' -CaseSensitive | Select-Object -ExpandProperty Line
          $content | ForEach-Object {$_ -replace $imageTagLine, "  tag: $(SetOutputVariables.version)"} | Set-Content $(footingappValuesFilePath)
      }
      catch
      {
        Write-Error "Raised error when executing code in location $(Get-Location) with error $($Error[0].Exception.Message)"
        throw
      }
    name: UpdateChartYamlFiles

  - task: DockerCompose@0
    name: DockerComposeBuild
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: '$(azureSubscription)'
      azureContainerRegistry: '{"loginServer":"$(azureContainerRegistryName).azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureResourceGroup)/providers/Microsoft.ContainerRegistry/registries/$(azureContainerRegistryName)"}'
      dockerComposeFilePath: '$(dockerComposeFilePath)'
      action: 'Build services'
      arguments: '--build-arg version=$(SetOutputVariables.fullVersion) --build-arg assembly_version=$(SetOutputVariables.assemblyVersion) --build-arg configuration=$(buildConfiguration)'
      dockerComposeFileArgs: |
        DOCKER_IMAGE_VERSION_TAG=$(SetOutputVariables.version)
      includeLatestTag: true

  - task: DockerCompose@0
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: DockerComposePush
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: '$(azureSubscription)'
      azureContainerRegistry: '{"loginServer":"$(azureContainerRegistryName).azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureResourceGroup)/providers/Microsoft.ContainerRegistry/registries/$(azureContainerRegistryName)"}'
      dockerComposeFilePath: '$(dockerComposeFilePath)'
      action: 'Push services'
      dockerComposeFileArgs: |
        DOCKER_IMAGE_VERSION_TAG=$(SetOutputVariables.version)
      includeLatestTag: true

  - task: HelmInstaller@0
    name: HelmInstall
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    inputs:
      helmVersion: '$(helmVersion)'
      installKubectl: true
      kubectlVersion: '$(kubectlVersion)'

  - task: HelmDeploy@0
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: HelmPushToCR
    inputs:
      azureSubscriptionForACR: '$(azureSubscription)'
      azureResourceGroupForACR: '$(azureResourceGroup)'
      azureContainerRegistry: '$(azureContainerRegistryName).azurecr.io'
      command: 'save'
      chartNameForACR: 'footingapp:$(SetOutputVariables.version)'
      chartPathForACR: '$(footingappChartPath)'


- job: DraftReleaseAndDeployToStaging
  dependsOn:
  - BuildAndPushToContainerRegistry
  variables:
    deployVersion: $[ dependencies.BuildAndPushToContainerRegistry.outputs['SetOutputVariables.version'] ]
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: GitHubRelease@1
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: CreateDraftRelease
    inputs:
      gitHubConnection: '$(gitHubServiceConnection)'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'v$(deployVersion)'
      title: 'v$(deployVersion)'
      isDraft: true
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'

  - task: HelmInstaller@0
    name: HelmInstall
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    inputs:
      helmVersion: '$(helmVersion)'
      installKubectl: true
      kubectlVersion: '$(kubectlVersion)'

  - script: 'helm dependency update $(footingappChartPath)'
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: HelmDependencyUpdate

  - task: HelmDeploy@0
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: HelmUpgrade
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscription: '$(azureSubscription)'
      azureResourceGroup: '$(azureResourceGroup)'
      kubernetesCluster: '$(nonProdKubernetesCluster)'
      namespace: '$(stagingDeployNamespace)'
      command: 'upgrade'
      releaseName: '$(stagingReleaseName)'
      chartType: 'FilePath'
      chartPath: '$(footingappChartPath)'
      chartVersion: '$(deployVersion)'
      updateDependency: true
      overrideValues: |
          ingress.hosts[0].host=$(stagingFootingHost)
          ingress.hosts[0].paths[0]=/
          ingress.tls[0].hosts[0]=$(stagingFootingHost)
          ingress.tls[0].secretName=$(footingTlsSecretName)
          ingress-nginx.controller.service.loadBalancerIP="$(stagingLoadBalancerIP)"


- job: GetApproval
  dependsOn: DraftReleaseAndDeployToStaging
  continueOnError: true
  pool: server
  timeoutInMinutes: 6
  steps: []


- job: DeployToProd
  dependsOn:
    - DraftReleaseAndDeployToStaging
    - GetApproval
  condition: eq(dependencies.GetApproval.result, 'Succeeded')
  continueOnError: true
  variables:
    deployVersion: $[ dependencies.BuildAndPushToContainerRegistry.outputs['SetOutputVariables.version'] ]
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: HelmInstaller@0
    name: HelmInstall
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    inputs:
      helmVersion: '$(helmVersion)'
      installKubectl: true
      kubectlVersion: '$(kubectlVersion)'

  - bash: |
      export HELM_EXPERIMENTAL_OCI=1
      helm chart pull $(azureContainerRegistryName).azurecr.io/helm/footingapp:$(deployVersion)
      helm chart export $(registryServerName)/helm/footingapp:$(deployVersion) --destination $(footingappChartPath)
      helm dependency update $(footingappChartPath)
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
    name: HelmGetChartAndUpdateDependencies

  - task: HelmDeploy@0
    name: HelmUpgrade
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscription: '$(azureSubscription)'
      azureResourceGroup: '$(azureResourceGroup)'
      kubernetesCluster: '$(prodKubernetesCluster)'
      namespace: '$(prodDeployNamespace)'
      command: 'upgrade'
      releaseName: '$(prodReleaseName)'
      chartType: 'FilePath'
      chartPath: '$(footingappChartPath)'
      chartVersion: '$(deployVersion)'
      updateDependency: true
      overrideValues: |
          ingress.hosts[0].host=$(prodFootingHost)
          ingress.hosts[0].paths[0]=/
          ingress.hosts[1].host=$(prodWwwFootingHost)
          ingress.hosts[1].paths[0]=/
          ingress.tls[0].hosts[0]=$(prodFootingHost)
          ingress.tls[0].secretName=$(footingTlsSecretName)
          ingress.tls[1].hosts[0]=$(prodWwwFootingHost)
          ingress.tls[1].secretName=$(footingWwwTlsSecretName)
          ingress-nginx.controller.service.loadBalancerIP="$(prodLoadBalancerIP)"


- job: RemoveDraftRelease
  dependsOn:
    - BuildAndPushToContainerRegistry
    - GetApproval
    - DeployToProd
  condition: |
    or
    (
      ne(dependencies.GetApproval.result, 'Succeeded'),
      ne(dependencies.DeployToProd.result, 'Succeeded')
    )
  variables:
    deployVersion: $[ dependencies.BuildAndPushToContainerRegistry.outputs['SetOutputVariables.version'] ]
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: GitHubRelease@1
    name: DeleteFailedDraftRelease
    inputs:
      gitHubConnection: '$(gitHubServiceConnection)'
      repositoryName: '$(Build.Repository.Name)'
      action: 'delete'
      tag: 'v$(deployVersion)'


- job: UpdateToNonDraftRelease
  dependsOn:
    - BuildAndPushToContainerRegistry
    - GetApproval
    - DeployToProd
  condition: |
    and
    (
      eq(dependencies.GetApproval.result, 'Succeeded'),
      eq(dependencies.DeployToProd.result, 'Succeeded')
    )
  variables:
    deployVersion: $[ dependencies.BuildAndPushToContainerRegistry.outputs['SetOutputVariables.version'] ]
  steps:
  - task: GitHubRelease@1
    name: UpdateToNonDraftRelease
    inputs:
      gitHubConnection: '$(gitHubServiceConnection)'
      repositoryName: '$(Build.Repository.Name)'
      action: 'edit'
      target: '$(Build.SourceVersion)'
      tag: 'v$(deployVersion)'
      assetUploadMode: 'replace'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
