# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureContainerRegistryName: 'crvemotueus2'
  azureContainerRegistryUrl: '$(azureContainerRegistryName).azurecr.io'

  buildConfiguration: Release
  timestamp: $(Get-Date -Format yyyyMMddTHHmmssfffffffZ)

  dockerComposeFile: 'src/docker-compose.yml'
  vemotuappChartPath: 'src/vemotuapp'
  vemotuappChartFilePath: '$(vemotuappChartPath)/Chart.yaml'
  vemotuappValuesFilePath: '$(vemotuappChartPath)/values.yaml'

  vemotuTlsSecretName: 'vemotu-com-tls'
  remeterTlsSecretName: 'remeter-org-tls'

  stagingDeployNamespace: vemotu-staging
  stagingReleaseName: vemotuapp-staging
  stagingVemotuHost: staging.vemotu.com
  stagingRemeterHost: staging.remeter.org
  stagingLoadBalancerIP: 52.138.105.11

  prodDeployNamespace: vemotu-prod
  prodReleaseName: vemotuapp-prod
  prodVemotuHost: prod.vemotu.com
  prodRemeterHost: prod.remeter.org
  stagingLoadBalancerIP: 52.184.202.52

steps:
<<<<<<< Updated upstream
=======
- checkout: self
  name: CheckoutMainBranchAndPersistCredentials
  persistCredentials: true

>>>>>>> Stashed changes
- script: |
    echo "##vso[task.setvariable variable=versionPrefix]$(cat src/version)"
  name: ReadVersionFromFile

- powershell: |
    $date=$(Get-Date -Format yyyyMMddTHHmmssfffffffZ);
    Write-Host "##vso[task.setvariable variable=timestamp]$date"
  name: SetTimestamp

- script: |
    echo "##vso[task.setvariable variable=version;isOutput=true]$VERSIONPREFIX"
    echo "##vso[task.setvariable variable=fullVersion;isOutput=true]$VERSIONPREFIX+build.$(Build.BuildId)-timestamp.$TIMESTAMP"
    echo "##vso[task.setvariable variable=assemblyVersion;isOutput=true]$VERSIONPREFIX.$(Build.BuildId)"
    echo "##vso[task.setvariable variable=loadBalancerIP;isOutput=true]$(stagingLoadBalancerIP)"
  name: SetOutputVariables

- powershell: |
    $content = Get-Content $(vemotuappChartFilePath)
    $versionLine = $content | Select-String -Pattern '^version:' -CaseSensitive | Select-Object -ExpandProperty Line
    $appVersionLine = $content | Select-String -Pattern '^appVersion:' -CaseSensitive | Select-Object -ExpandProperty Line
    $content | ForEach-Object {$_ -replace $versionLine, "version: $(SetOutputVariables.version)"} | ForEach-Object {$_ -replace $appVersionLine, "appVersion: $(SetOutputVariables.version)"} | Set-Content $(vemotuappChartFilePath)

    $content = Get-Content $(vemotuappValuesFilePath)
    $imageTagLine = $content | Select-String -Pattern '^  tag:' -CaseSensitive | Select-Object -ExpandProperty Line
    $content | ForEach-Object {$_ -replace $imageTagLine, "  tag: $(SetOutputVariables.version)"} | Set-Content $(vemotuappValuesFilePath)
  name: UpdateChartYamlFiles

- task: DockerCompose@0
  name: DockerComposeBuild
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: '$(azureSubscription)'
<<<<<<< Updated upstream
    azureContainerRegistry: '{"loginServer":"crvemotueus2.azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureResourceGroup)/providers/Microsoft.ContainerRegistry/registries/crvemotueus2"}'
    dockerComposeFile: 'src/docker-compose.yml'
=======
    azureContainerRegistry: '{"loginServer":"$(azureContainerRegistryName).azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureResourceGroup)/providers/Microsoft.ContainerRegistry/registries/$(azureContainerRegistryName)"}'
    dockerComposeFilePath: 'src/docker-compose.yml'
>>>>>>> Stashed changes
    action: 'Build services'
    arguments: '--build-arg version=$(SetOutputVariables.fullVersion) --build-arg assembly_version=$(SetOutputVariables.assemblyVersion) --build-arg configuration=$(buildConfiguration)'
    dockerComposeFileArgs: |
      DOCKER_IMAGE_VERSION_TAG=$(SetOutputVariables.version)
    includeLatestTag: true

- task: DockerCompose@0
  condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
  name: DockerComposePush
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: '$(azureSubscription)'
<<<<<<< Updated upstream
    azureContainerRegistry: '{"loginServer":"crvemotueus2.azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureResourceGroup)/providers/Microsoft.ContainerRegistry/registries/crvemotueus2"}'
    dockerComposeFile: 'src/docker-compose.yml'
=======
    azureContainerRegistry: '{"loginServer":"$(azureContainerRegistryName).azurecr.io", "id" : "/subscriptions/$(azureSubscriptionUuid)/resourceGroups/$(azureResourceGroup)/providers/Microsoft.ContainerRegistry/registries/$(azureContainerRegistryName)"}'
    dockerComposeFilePath: 'src/docker-compose.yml'
>>>>>>> Stashed changes
    action: 'Push services'
    dockerComposeFileArgs: |
      DOCKER_IMAGE_VERSION_TAG=$(SetOutputVariables.version)
    includeLatestTag: true

- task: HelmInstaller@0
  name: HelmInstall
  condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
  inputs:
    helmVersion: '3.4.1'
    installKubectl: true
    kubectlVersion: '1.19.4'

- task: HelmDeploy@0
  condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
  name: HelmPushToCR
  inputs:
    azureSubscriptionForACR: '$(azureSubscription)'
    azureResourceGroupForACR: 'rg-vemotu-eus2-001'
    azureContainerRegistry: '$(azureContainerRegistryName).azurecr.io'
    command: 'save'
    chartNameForACR: 'vemotuapp:$(SetOutputVariables.version)'
    chartPathForACR: '$(vemotuappChartPath)'

- script: 'helm dependency update src/vemotuapp'
  condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
  name: HelmDependencyUpdate

- task: HelmDeploy@0
  condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI', 'Schedule'))
  name: HelmUpgrade
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '$(azureSubscription)'
    azureResourceGroup: '$(azureResourceGroup)'
    kubernetesCluster: '$(nonProdKubernetesCluster)'
    namespace: '$(stagingDeployNamespace)'
    command: 'upgrade'
    releaseName: '$(stagingReleaseName)'
    chartType: 'FilePath'
    chartPath: 'src/vemotuapp'
    chartVersion: '$(SetOutputVariables.version)'
    updateDependency: true
    overrideValues: |
        ingress.hosts[0].host=$(stagingVemotuHost)
        ingress.hosts[0].paths[0]=/
        ingress.hosts[1].host=$(stagingRemeterHost)
        ingress.hosts[1].paths[0]=/
        ingress.tls[0].hosts[0]=$(stagingVemotuHost)
        ingress.tls[0].secretName=$(vemotuTlsSecretName)
        ingress.tls[1].hosts[0]=$(stagingRemeterHost)
        ingress.tls[1].secretName=$(remeterTlsSecretName)
        ingress-nginx.controller.service.loadBalancerIP="$(stagingLoadBalancerIP)"
