# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main
      - develop
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureContainerRegistryName: 'crvemotueus2'
  azureContainerRegistryUrl: '$(azureContainerRegistryName).azurecr.io'
  dockerComposeFile: 'src/docker-compose.yml'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'remeterRegistry001'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
