<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'Blah.Server' " />
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.5" />
    <PackageReference Include="Blazored.LocalStorage" Version="2.1.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Remeter.Portal.Shared.csproj" />
    <ProjectReference Include="..\Client\Remeter.Portal.Client.csproj" />
  </ItemGroup>
</Project>