<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latestmajor</LangVersion>
    <DockerComposeProjectPath>../../../docker-compose.dcproj</DockerComposeProjectPath>
    <UserSecretsId>7056975d-15dc-4ed3-8c74-bd10f8546447</UserSecretsId>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'Default Browser' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'Debug Browser' " />
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="3.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Remeter.Portal.Shared.csproj" />
    <ProjectReference Include="..\Client\Remeter.Portal.Client.csproj" />
  </ItemGroup>
</Project>
