apiVersion: v2
name: footingapp
description: A Helm chart for the Footing application
type: application
version: 0.1.0
appVersion: "2.0.0"

dependencies:
  - name: ingress-nginx
    version: 3.12.0
    repository: https://kubernetes.github.io/ingress-nginx
