version: '3.8'

services:
  remeter.portal.server:
    image: ${DOCKER_REGISTRY-}remeterportal
    build:
      context: .
      dockerfile: Remeter/Portal/Server/Dockerfile
      args:
      - configuration=Debug
      - version=0.0.1
      - assembly_version=0.0.1.0
