version: '3.4'

services:
  footing:
    image: ${DOCKER_REGISTRY-}footing:${DOCKER_IMAGE_VERSION_TAG-latest}
    build:
      context: .
      dockerfile: Footing/Dockerfile
      args:
        - version=${version-0.0.0-local}
        - assembly_version=${assembly_version-0.0.0.0}
        - configuration=${configuration-Release}
